---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  data_bags_path: "./data_bags/"

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: centos-7.1
  run_list:
  - recipe[yum]

- name: centos-6.6
  run_list:
  - recipe[yum]


suites:
- name: default
  run_list:
  - recipe[users::sysadmins]
  - recipe[oh-my-zsh]
  attributes: {}
